name: Secure CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Gitleaks
      uses: gitleaks/gitleaks-action@v2

    - name: Build Docker
      run: docker build -t secureapp .



