name: Secure CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Gitleaks
      uses: gitleaks/gitleaks-action@v2
      with:
        fail: true

    - name: Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: "p/owasp-top-ten"
      env:
        SEMGREP_FAIL_ON: error

    - name: OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: "SecureRelease-Demo"
        path: "."
        format: "HTML"
        failOnCVSS: 7

    - name: Build Docker
      run: docker build -t secureapp .



